imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

parameters:
    twitter.hashtags: ['GameJamAlicante', 'GameJamUA', 'GJUA']
    twitter.username: gamejamua

framework:
    translator:      { fallback: es }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: false
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        site:
            main_email: %main_email%
            irc:
                server: 'irc.quakenet.org'
                channel: '#gamejamalicante'
            name: GameJam Alicante
            twitter:
                name: %twitter.username%
                url: http://twitter.com/GameJamUA
                hashtags: %twitter.hashtags%
            facebook:
                url: ~

assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    filters:
        cssrewrite:
            apply_to: "\.css$"

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: GJA\GameJam\UserBundle\Entity\User
    registration:
        form:
            type: gamejam_user_register
    from_email:
        address: contacto@gamejamua.com
        sender_name: GameJam Alicante

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            legacy:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "gamejam_old"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool: { type: memory }

services:
 twig.extension.text:
     class: Twig_Extensions_Extension_Text
     tags:
         - { name: twig.extension }

stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true

mz_mail_chimp:
    api_key: %mailchimp_api_key%
    default_list: %mailchimp_list_members%
    ssl: true

google:
    analytics:
        trackers:
            default:
                name:      default
                accountId: %ga_tracker%
                domain:    .%domain%
                trackPageLoadTime: true

ornicar_gravatar: ~

avalanche_imagine:
    filters:
        sponsor_compo_mini:
            type:    relative_resize
            options: { heighten: 60 }
        game_gallery_mini:
            type: relative_resize
            options: { heighten: 65 }
        game_gallery_preview:
            type: relative_resize
            options: { heighten: 300 }

presta_sitemap:
    dumper_base_url: "https://www.%domain%/"

amnl_router_unslash:
    permanent: true
    public: false

jms_payment_core:
    secret: %secret%

jms_payment_paypal:
    username: %paypal_username%
    password: %paypal_password%
    signature: %paypal_signature%
    debug: %paypal_debug%

hwi_oauth:
    connect:
        account_connector: gamejam.user.security.user_provider
    firewall_name: main
    connect:
        confirmation: false
    resource_owners:
        twitter:
            type:                twitter
            client_id:           %oauth.twitter_client_id%
            client_secret:       %oauth.twitter_client_secret%
            paths:
                profilepicture: profile_image_url_https

game_jam_user:
    oauth_tokens: %oauth%
    oauth_services: ['twitter']

endroid_twitter:
    consumer_key: %oauth.twitter_client_id%
    consumer_secret: %oauth.twitter_client_secret%
    access_token: %twitter_access_token%
    access_token_secret: %twitter_access_token_secret%