_sitemap:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /

gamejam_frontend:
    resource: "@GameJamCompoBundle/Controller/"
    type: annotation

gamejam_user:
    resource: "@GameJamUserBundle/Controller/"
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /panel/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /registro

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /recordar-password

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /panel

_imagine:
    resource: .
    type:     imagine