security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        legacy_encoder:
            id: gamejam.user.security.legacy_password_encoder

    role_hierarchy:
        ROLE_USER: []
        ROLE_MEMBER: ROLE_USER
        ROLE_SUPER_MEMBER: ROLE_MEMBER
        ROLE_OLD_STAFF: ROLE_USER
        ROLE_JANITOR: [ROLE_USER, ROLE_STAFF]
        ROLE_JURY: ROLE_USER
        ROLE_COORDINATOR: [ROLE_USER, ROLE_STAFF]
        ROLE_ADMIN: [ROLE_USER, ROLE_JANITOR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        health:
            pattern: ^/monitor/health
            anonymous: ~
            http_basic:
                realm: "Secured Area"
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            switch_user: true
            remember_me:
                key: %secret%
                lifetime: 604800
                path: /
            pattern: ^/
            form_login:
                provider: fos_userbundle
                default_target_path: gamejam_compo_frontend
                always_use_default_target_path: false
                login_path: fos_user_security_login
            oauth:
                resource_owners:
                    twitter: "/oauth/login/check-twitter"
                login_path: fos_user_security_login
                failure_path: fos_user_security_login
                oauth_user_provider:
                    service: gamejam.user.security.user_provider
                always_use_default_target_path: true
                default_target_path: /
                use_referer: true
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/compos/.*/(inscribirse|team|modificar-inscripcion), roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/panel, roles: ROLE_USER }
        - { path: ^/juegos/.*/(dar-monedas|like), roles: ROLE_USER }
        - { path: ^/monitor/health, role: ROLE_SUPER_ADMIN }